#ifndef DISTRIBUTEDMONITOR_DISTRIBUTEDCONDITIONALVARIABLE_H
#define DISTRIBUTEDMONITOR_DISTRIBUTEDCONDITIONALVARIABLE_H


class DistributedConditionalVariable {
private:

};


#endif //DISTRIBUTEDMONITOR_DISTRIBUTEDCONDITIONALVARIABLE_H
